{% set name = "fontpens" %}
{% set version = "0.2.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/fontPens-{{ version }}.zip
  sha256: a6d9a14573b3450f3313d69523f9006028c21fc7aef5d35333b87aab7f2b41fd

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - fonttools >=3.32.0

test:
  imports:
    - fontPens
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/robofab-developers/fontPens
  summary: A collection of classes implementing the pen protocol for manipulating glyphs.
  license: BSD-3-Clause
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - thewchan
