schema_version: 1

context:
  name: fontpens
  version: "0.4.0"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 69be9a81087dd59f1b8dee3f1fc8f7cd4693980ab45852feb496cbb28fbd93cb

build:
  number: 0
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python ${{ python_min }}.*
    - pip
    - hatchling
    - hatch-vcs
  run:
    - python >=${{ python_min }}
    - fonttools >=4.40

tests:
  - python:
      imports:
        - fontPens
      pip_check: true
      python_version:
        - ${{ python_min }}.*
        - "*"

about:
  summary: A collection of classes implementing the pen protocol for manipulating glyphs.
  license: BSD-3-Clause
  license_file: LICENSE.txt
  homepage: https://github.com/robofab-developers/fontPens

extra:
  recipe-maintainers:
    - thewchan
